repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-json
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: check-ast
      - id: check-added-large-files
        args: ["--maxkb=2500"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.3.5"
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]
